### PR TITLE
CLI and other things

### PR DESCRIPTION
**Pull request by RosiePuddles**
I like hbml. so, i did some things to help out a bit:
- improved the parser speed ~10x (2,514 ops/sec ±0.59% to 26,366 ops/sec ±0.17%)
- make it a command line app
- documented things

the cli has the following:
- hbml to html builder with command line arg parsing and validating
- basic hbml linting with command line arg parsing and validating
- project based options to set cli arg values by default

For a better and full description see the usage.md file

it's still able to be used as a module as well

For anyone wondering, writing a non-recursive parser is possible but it doesn't inprove performance over my current one. the code is also slightly confusing to understand and would be annoying to maintain so I opted to not do that

### CODE REVIEW

**Review by heyitsdoodler — CHANGES_REQUESTED** [review]
Hi,

First of all I just want to say that I really appreciate all the work you've put into this. I can tell you're obviously enthusiastic on top of being substantially more capable than I currently am.

I looked through your pull request and it looks great aside from a couple small issues that I'm hoping you have time to address.

1. My version of the parser allows for non root content to be parsed, so someone could input `div {"Text"}` into the parser and get back `<div>Text</div>` without the need for the rest of the structure of a full HBML/HTML. 
    - If you believe that it would be better to require the root as you currently do I am open to this.
    - Note: another side effect of not allowing other elements at the root level is that comments are no longer able to be placed there.
2. Comments are not being handled properly, `/* Test */` becomes `<!-- /* test  -->` in the output.
3. I made some substantial changes to how attributes are handled in the latest commit (the only commit that is ahead of your repo). Attributes are now extracted out for better handling rather than just transferring the text between the square brackets [] directly to the html, this also avoids whitespace/newlines from being unnecessarily preserved over to the output HTML. My updated parser allows all three methods of making strings ("'\`) for attribute values as well as omitting the quotes for unbroken values. If you could take some time to integrate the updated version of the parser into your vastly superior version that would be greatly appreciated. Here are a couple examples of how this is meant to work.
    - ```link[href=https://cdn.example.com/styles.css]``` -> ```<link href="https://cdn.example.com/styles.css"/>```
    - 
```
div[
           attribute
           attribute1=testValue
           attribute2="another test value"
           attribute3='third test value'
           attribute4=`different test value`
]
```
-> 
```
<div attribute attribute1="testValue" attribute2="another test value" attribute3="third test value" attribute4="different test value"></div>
```



Once again I want to reiterate my appreciation for you taking time out of your day to improve HBML.

**Comment by RosiePuddles** [comment]
I'm going to remove the requiring a root for slightly different reasons (see below) the comments not working properly is pretty easy to fix. And I'm going to rewrite my attribute handling as well for the same reason as removing requiring root

The reason I said before:
To really make this as powerful as I think it can be I think adding in simple macros could be really useful. At the moment I've only really considered "tag macros" which are just tags with default attributes and classes. Macros would be indicated by a ':' prefix meaning `:root` would be a macro with the default lang=en attribute. If you've got any thought a on this it'd be nice to hear them

**Comment by heyitsdoodler** [comment]
I agree with your implementation of macros, they could perhaps be more powerful if they allowed contents and multiple nested elements but I'm not sure how this could made fast and useful. 

We could also consider using --tag-name for definition of macros since this brings macros in line with how CSS variables are defined, thus furthering the goal of making the syntax intuitively similar.


p.s.
Do you have any specific resources to recommend pertaining to language lexing, tokenizing, and parsing that could aid me in improving my own ability, I'm a novice cs student so my abilities are still rather lacking.

Since this is unrelated to the pull request I'd be happy to discuss it separately on Discord or another platform.

**Comment by RosiePuddles** [comment]
i'd be happy to give you some pointers for parsing on discord if you'd like?
also do you have any examples of how you might use the css-style macro definitions?

**Comment by heyitsdoodler** [comment]
Here is a quick example of how this could work, I've put the definitions directly inside :root for clarity but I suppose they could go anywhere.

This is a bunch of ideas thrown together and definitely has room for improvement.

```hbml
:root {
    
    /* Simple tag macro with equivalent functionality to your current concept */
    
    --tag_macro > div.class
    
    /* A macro that is just a string */
    
    --string_macro > "Hello World!"
    
    /* A complex macro, my thoughts are that for a simple tag macro with no {} or > for children
    implicity has the children of the macro when it is used */
    
    --complex_macro > .complex-macro {
        h1 > :string_macro
        div {
            :children
        }
    }
    /* :children is a special macro that is always defined as the contents passed into the macro */

    
    --shadow_title > "Has not been shadowed"
    --shadow_body > "Has not been shadowed"
    
    --macro_with_shadowing > {
        h2 > :shadow_title
        :shadow_body
    }
    
    
    --comment_macro_because_yolo > /* How did we get here? */

    head {
        title > "Macro concepting"
    }
    
    body {
        /* I'll put the macro usage followed by equivalent HBML like you did with your examples */
        
        :tag_macro {
            "Some text"
            br
            "More text"
        }
        .class {
            "Some text"
            br
            "More text"
        }
        
        :complex_macro#myMacro {
            ul {
                li > "Item 1"
                li > "Item 2"
            }
        }  
        #myMacro.complex-macro {
            h1 > "Hello World!"
            div {
                ul {
                    li > "Item 1"
                    li > "Item 2"
                } 
            }
        }
        
        :macro_with_shadowing {
            --shadow_title > "My Cool Title!"
            --shadow_body > {
                .first .second .third
            }
        }
        {
            h1 > "My Cool Title!"
            {
                .first .second .third
            }
        }
        
        :comment_macro_because_yolo
        /* How did we get here? */
    }
}
```

To sum it up -- is used for definitions : is used for using the macro.

Another possible idea shown here is that definitions could exist within the scope of the block where they are defined, if a macro used inside another macro follows the definition of the block where the macro is used this could allow shadowing of macro definitions for more customizability.

I think that given the nature of macros, they should only have one top level element. So it makes sense to have the ">" character to indicate the single "child" nature of the definition, that single child becoming the root of the macro.

Also my discord is MinecraftDoodler#8834

**Comment by heyitsdoodler** [comment]
Just noticed another issue with your implementation. Classes aren't being properly handled and are being appended to the id.

**Review by heyitsdoodler — APPROVED** [review]

**Pull request merged**
